//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


Suggestion = function(args) {
  this.suggestion = null;
  this.payload = null;
  if (args) {
    if (args.suggestion !== undefined) {
      this.suggestion = args.suggestion;
    }
    if (args.payload !== undefined) {
      this.payload = args.payload;
    }
  }
};
Suggestion.prototype = {};
Suggestion.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.suggestion = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.payload = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Suggestion.prototype.write = function(output) {
  output.writeStructBegin('Suggestion');
  if (this.suggestion !== null && this.suggestion !== undefined) {
    output.writeFieldBegin('suggestion', Thrift.Type.STRING, 1);
    output.writeString(this.suggestion);
    output.writeFieldEnd();
  }
  if (this.payload !== null && this.payload !== undefined) {
    output.writeFieldBegin('payload', Thrift.Type.STRING, 2);
    output.writeString(this.payload);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};
